name: ECS Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          docker build -t 700740239256.dkr.ecr.ap-south-1.amazonaws.com/nodejsapp:latest .
          docker push 700740239256.dkr.ecr.ap-south-1.amazonaws.com/nodejsapp:latest
          

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster nodejsapp --service nodejsapp --force-new-deployment

